### ISSUE TITLE
Few issues,

### ISSUE THREAD

**Issue by AddAntiCheatt** [psZachary/onward-public#1]
One, Tazer is the ONLY way to really down me while in god mode. Anyway to fix this would be a huge upgrade. 

Two, i would like to see the tazer and grenade launcher have the fully automatic super fire rate buff applied to them too.

and last but not least, add a way to bypass the kicks. or have the teamkilling kick pop ups not effect you, making u non kickable. 

hope to see this release get the attention it needs, btw. i was the guy who blew this up and met you in the game at one point, i know ur name is JB. have a good day man, hope to see this get better with more features like flying. and even faster speed.

**Comment by psZachary** [comment]
I plan on adding more features in the future possibly, btw the JB guy you supposedly met was not me, I hardly play onward, only for testing cheat. However I am the original creator, and maintainer of this cheat.

**Comment by AddAntiCheatt** [comment]
Huh, Weird, well i got a ban today after days of rage cheating in shooting range, fixing to just make a new account and get it again once a new update comes out, thanks!
