### ISSUE TITLE
Update 1.9 - Need new offsets

### ISSUE THREAD

**Issue by JimmyLongJohns** [psZachary/onward-public#3]
Nothings working and shits crashing because of the new update, please update the offsets thx papi

**Comment by JimmyLongJohns** [comment]
or tell me what files I need to select in il2cpp

**Comment by JimmyLongJohns** [comment]
I used il2cpp but Idk what the fuck to do with the script data 👯

**Comment by JimmyLongJohns** [comment]
> I'll fix later tonight

thank you also can you add my discord pls JimmyLongJohns#8510

only so I can figure out how to get the offsets when you stop working on the cheat :3

**Comment by doogal50** [comment]
yo is this fixed at all? idk how any of this coding stuff works but if there's any way for me to fix it myself i'd be happy to
dyanator15#1247

**Comment by psZachary** [comment]
Please be patient will be fixed within a week, been extremely busy

**Comment by JimmyLongJohns** [comment]
> Please be patient will be fixed within a week, been extremely busy

Do the update bossSssS XD

**Comment by psZachary** [comment]
> > Please be patient will be fixed within a week, been extremely busy
> 
> 
> 
> Do the update bossSssS XD

Busy the whole week, expect the latest fix date to be November 14th

**Comment by JimmyLongJohns** [comment]
> > > Please be patient will be fixed within a week, been extremely busy
> > 
> > 
> > Do the update bossSssS XD
> 
> Busy the whole week, expect the latest fix date to be November 14th

you should post you updating it so we can get the vid and use it to update it when you cant

**Comment by psZachary** [comment]
Updated
