### ISSUE TITLE
Erroring not injecting

### ISSUE THREAD

**Issue by skekaqua** [psZachary/onward-public#7]
![image](https://user-images.githubusercontent.com/120623445/207799561-01bb2f0c-2e4e-4f15-a13c-5dfc236fc558.png)

**Comment by psZachary** [comment]
I'll look into it this weekend

**Comment by skekaqua** [comment]
> I'll look into it this weekend

Is was **VCRUNTIME140_1.dll** installing _Microsoft Visual C++ 2015 - 2019 Redistributable_ fixes it.
