### ISSUE TITLE
Crashing issue and more

### ISSUE THREAD

**Issue by Lucianpro124** [psZachary/onward-public#8]
There is a issue where when I enable the cheats and go into a game its fine but when I leave the game crashes and also when I enable weapon mods. I spawn in and don't have any guns than I press change loadout but its just a black screen, please fix these issues and the dll file will be perfect!

**Comment by Lucianpro124** [comment]
tell me when I should try using the cheats in a public server again.

**Comment by psZachary** [comment]
As stated in previous issues, it may or may not be fixed later when I have the chance

**Comment by Lucianpro124** [comment]
ok thanks for responding I hope u can fix it as soon as possible thanks!
