### ISSUE TITLE
PATCHED

### ISSUE THREAD

**Issue by david500900** [psZachary/onward-public#9]
keeps crashing think it got patched sadly

**Comment by psZachary** [comment]
Please elaborate more and don't create inadequate issues on the repo. I need more details. Does it crash on injection? Any specific features? Saying "it crashes" is uninformative and is not helpful.

**Comment by psZachary** [comment]
And to elaborate on the last comment I left, I injected after you created the issue to check the validity of your claim, and it worked without crashing or issues.
